In [1]:
import numpy as np

In [3]:
#1번

v = np.array([1,-1,0])
w = np.array([2,0,1])

w = w.astype('float64')

a = np.inner(v,w)
b = np.inner(w,w)

c = (a/b)*w

d = v-c

e = np.inner(d,w)

print('(1) v,w 내적:',a,'\n')
print('(2) proj_w_v:',c,'\n')
if int(e) == 0 : print('(3)수직입니다.')

(1) v,w 내적: 2.0 

(2) proj_w_v: [0.8 0.  0.4] 

(3)수직입니다.


In [4]:
#2번

A = np.array([[3,4,5,-1],[0,1,2,-1],[2,5,-3,0]])
B = np.array([[2,-2,-3],[5,0,0],[-1,3,4],[7,2,-3]])

print('행렬곱 AB\n',np.matmul(A,B),'\n')
print('행렬곱 BA\n',np.matmul(B,A))

행렬곱 AB
 [[ 14   7  14]
 [ -4   4  11]
 [ 32 -13 -18]] 

행렬곱 BA
 [[  0  -9  15   0]
 [ 15  20  25  -5]
 [  5  19 -11  -2]
 [ 15  15  48  -9]]


In [6]:
#3번

A = np.array([[2,1],[1,-1]])

for i in range(2,11):
    print("----------A의",i,"승-----------")
    A = np.matmul(A,A)
    B = np.transpose(A)
    print(A,'\n',B)

----------A의 2 승-----------
[[5 1]
 [1 2]] 
 [[5 1]
 [1 2]]
----------A의 3 승-----------
[[26  7]
 [ 7  5]] 
 [[26  7]
 [ 7  5]]
----------A의 4 승-----------
[[725 217]
 [217  74]] 
 [[725 217]
 [217  74]]
----------A의 5 승-----------
[[572714 173383]
 [173383  52565]] 
 [[572714 173383]
 [173383  52565]]
----------A의 6 승-----------
[[ 1580704917  1038566457]
 [ 1038566457 -1534994454]] 
 [[ 1580704917  1038566457]
 [ 1038566457 -1534994454]]
----------A의 7 승-----------
[[-387869846 2046260295]
 [2046260295 2063283861]] 
 [[-387869846 2046260295]
 [2046260295 2063283861]]
----------A의 8 승-----------
[[1225347989  701272505]
 [ 701272505 -878469526]] 
 [[1225347989  701272505]
 [ 701272505 -878469526]]
----------A의 9 승-----------
[[ -913372054 -1807724473]
 [-1807724473   214834069]] 
 [[ -913372054 -1807724473]
 [-1807724473   214834069]]
----------A의 10 승-----------
[[-1481470059   -65681479]
 [  -65681479 -1284425622]] 
 [[-1481470059   -65681479]
 [  -65681479 -1284425622]]
