In [1]:
import numpy as np

In [2]:
A = np.array([ [1,3],[2,-1],[0,5] ])
B = np.array([ [7,-2,3],[0,5,-3] ])

C = [ [1,3],[2,-1],[0,5] ]
D = [ [7,-2,3],[0,5,-3] ]

In [3]:
def make_matmul(v,w):
    
    v_row = len(v)
    v_column = len(v[0])
    
    w_row = len(w)
    w_column = len(w[0])
    
    if v_column != w_row : return print("ERROR")
     
    output = []
    
    for i in range(0,v_row):
        row = []
        for j in range(0,v_row):
            value = 0
            for k in range(0,w_row):
                value += v[i,k]*w[k,j]
            row.append(value)
        output.append(row)
    
    return output

문제 1

In [4]:
print("numpy matmul :\n",np.matmul(B,A))
print("my matmul :\n",make_matmul(B,A))

numpy matmul :
 [[  3  38]
 [ 10 -20]]
my matmul :
 [[3, 38], [10, -20]]


문제 2

In [5]:
A = np.array([ [2,5],[2,3] ])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.75  1.25]
 [ 0.5  -0.5 ]]


In [6]:
A_A_inv = np.matmul(A,A_inv)
A_inv_A = np.matmul(A_inv,A)

print(A_A_inv,"\n\n",A_inv_A) # 항등행렬이 된다.

[[1. 0.]
 [0. 1.]] 

 [[1. 0.]
 [0. 1.]]


문제 3

In [7]:
def identity(n):
    
    output = []
    
    for i in range(0,n):
        row = []
        for j in range(0,n):
            if i == j : row.append(1)
            else : row.append(0)
        output.append(row)
    
    return output

In [8]:
identity(5)

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]